# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 0.8.0

package:
  name: robotframework-ghareports
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/r/robotframework-ghareports/robotframework_ghareports-${{ version }}.tar.gz
  sha256: 4f083f7b60966ddd8dbabe3a2939ca8c49400ffd628e7214c11fa4370136c468

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  python:
    entry_points:
      - ghareports = GHAReports.cli:main

requirements:
  host:
    - pdm-backend
    - pip
    - python ${{ python_min }}.*
  run:
    - python >=${{ python_min }}
    - robotframework >=4.0.0
    - wrapt

tests:
  - python:
      imports: GHAReports
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.13.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - ghareports --help

about:
  homepage: https://github.com/rasjani/robotframework-ghareports
  license_file: LICENSE
  license: GPL-3.0-or-later
  summary: Simple github action summary report for robotframework

extra:
  recipe-maintainers:
    - bollwyvl
